-- schema.sql: Define a estrutura completa do nosso banco de dados de estatísticas de MTG.

-- Tabela de Dimensão para Jogadores
CREATE TABLE IF NOT EXISTS Dim_Jogadores (
    ID_JOGADOR INTEGER PRIMARY KEY,
    NOME_JOGADOR VARCHAR(100) NOT NULL UNIQUE
);

-- Tabela de Dimensão para Comandantes
CREATE TABLE IF NOT EXISTS Dim_Comandantes (
    ID_COMANDANTE VARCHAR(36) PRIMARY KEY, -- Usaremos o Oracle ID do Scryfall (UUID)
    NOME_COMANDANTE_EN VARCHAR(255) NOT NULL,
    IDENTIDADE_DE_COR VARCHAR(5),
    TIPO_CARTA VARCHAR(255),
    URL_IMAGEM VARCHAR(255)
);

-- Tabela de Dimensão para Métodos de Eliminação
CREATE TABLE IF NOT EXISTS Dim_Metodos_Eliminacao (
    ID_METODO INTEGER PRIMARY KEY,
    CODIGO_METODO VARCHAR(1) NOT NULL UNIQUE,
    DESCRICAO_METODO VARCHAR(100) NOT NULL
);

-- Tabela Fato para Partidas
CREATE TABLE IF NOT EXISTS Fact_Partidas (
    ID_PARTIDA BIGINT PRIMARY KEY, -- Ex: 2025081101 (AAAAMMDD + sequencial)
    DATA_PARTIDA DATE,
    NUM_JOGADORES INTEGER,
    ID_JOGADOR_VENCEDOR INTEGER,
    FOREIGN KEY (ID_JOGADOR_VENCEDOR) REFERENCES Dim_Jogadores(ID_JOGADOR)
);

-- Tabela Fato para Eliminações
CREATE TABLE IF NOT EXISTS Fact_Desempenho_Partida (
    ID_DESEMPENHO INTEGER PRIMARY KEY,
    ID_PARTIDA BIGINT NOT NULL,
    ID_JOGADOR INTEGER NOT NULL,
    ID_COMANDANTE VARCHAR(36) NOT NULL,
    POSICAO INTEGER, -- 1 para vencedor, 2 para segundo, etc.
    PONTUACAO INTEGER,
    KILLS_COMBATE INTEGER,
    KILLS_COMANDANTE INTEGER,
    KILLS_NAO_COMBATE INTEGER,
    KILLS_OUTROS INTEGER,
    FOREIGN KEY (ID_PARTIDA) REFERENCES Fact_Partidas(ID_PARTIDA),
    FOREIGN KEY (ID_JOGADOR) REFERENCES Dim_Jogadores(ID_JOGADOR),
    FOREIGN KEY (ID_COMANDANTE) REFERENCES Dim_Comandantes(ID_COMANDANTE)
);